#!/bin/bash

if [ "${@}" ] ; then
	cd "$(wslpath "${@}")"
fi

if ! echo $PATH | grep -Fqi 'WINDOWS/System32:' ; then
	if ! echo $PATH | grep -Fqi 'AppData/Local/Microsoft/WindowsApps' ; then
		echo "Unable to find system-drive mount point from \$PATH. Please relaunch Pengwin from the Start Menu"
	fi

	SystemDrive="$(echo $PATH | sed 's|:|\n|g' | grep 'AppData/Local/Microsoft/WindowsApps' | cut -d$'\n' -f1 | sed 's|/Users/.*/AppData/Local/Microsoft/WindowsApps||g')"
	SystemRoot="$SystemDrive/WINDOWS"
	if echo $PATH | grep -Fqi '%SYSTEMROOT%' ; then
		PATH="$(echo $PATH | sed 's|/%SystemRoot%|'"$SystemRoot"'|gI')"
	else
		P_System32="$SystemRoot/System32"
		P_SystemRoot="$SystemRoot"
		P_Sys32Wbem="$P_System32/Wbem"
		P_Sys32PowerShell="$P_System32/WindowsPowerShell/v1.0"
		P_Sys32OpenSSH="$P_System32/OpenSSH"
		PATH="$PATH:$P_System32:$P_SystemRoot:$P_Sys32Wbem:$P_Sys32PowerShell:$P_Sys32OpenSSH"
	fi
	export PATH
fi

$(getent passwd $LOGNAME | cut -d: -f7) --login
