#!/bin/bash

if [ "${@}" ] ; then
	cd "$(wslpath "${@}")"
fi

# Proposed fix for PATH when user home has spaces (on Windows 10 1903+)
if echo $PATH | grep -Fqe '%USERPROFILE%' ; then
	if echo $PATH | grep -Fqe '/mnt/' ; then
		PATH="$(echo $PATH | sed 's|:/%USERPROFILE%/AppData/Local/Microsoft/WindowsApps||g')"
		export PATH
	else
		echo "Unable to find system drive from \$PATH. Please relaunch Pengwin from the Start Menu"
	fi
fi
if echo $PATH | grep -Fqe '%SYSTEMROOT%' ; then
	SystemDrive="$(echo $PATH | sed 's|:|\n|g' | grep 'AppData/Local/Microsoft/WindowsApps' | cut -d$'\n' -f1 | sed 's|/Users/.*/AppData/Local/Microsoft/WindowsApps||g')"
	SystemRoot="$SystemDrive/WINDOWS"
	PATH="$(echo $PATH | sed 's|/%SYSTEMROOT%|'"$SystemRoot"'|g')"
	export PATH
fi
if echo $PATH | grep -Fqe '%SystemRoot%' ; then
	SystemDrive="$(echo $PATH | sed 's|:|\n|g' | grep 'AppData/Local/Microsoft/WindowsApps' | cut -d$'\n' -f1 | sed 's|/Users/.*/AppData/Local/Microsoft/WindowsApps||g')"
	SystemRoot="$SystemDrive/WINDOWS"
	PATH="$(echo $PATH | sed 's|/%SystemRoot%|'"$SystemRoot"'|g')"
	export PATH
fi

$(getent passwd $LOGNAME | cut -d: -f7) --login
