#!/bin/bash

# environment

RESPONSE=""
CURDUR=""
TMPDIR=""
VERSION="1.2a"
wHomeWinPath=$(cmd.exe /c 'echo %HOMEDRIVE%%HOMEPATH%' 2>&1 | tr -d '\r')
wHome=$(wslpath -u "${wHomeWinPath}")

# define functions

function processarguments {
while [[ $# -gt 0 ]]
do
  case "$1" in
    --debug|-d|--verbose|-v)
      echo "Running in Debug mode"
      set -x
      shift
    ;;
    *)
      shift
    esac
done
}

function welcomeprompt {
whiptail --title "Welcome to WLinux" --msgbox "Thank you for supporting sustainable independent open source development.\n
WLinux comes with a core set of useful packages pre-installed, such as curl, git, and wslu. \n
wlinux-setup allows you to install additional hand-curated selections for WLinux and configure optional WSL-specific settings. \n
Many more packages are available via the apt package manager and optional pip, npm, and RubyGems package managers.\
" 15 96
}

function continueprompt {
if (whiptail --title "Continue setup?" --yesno "Would you like to continue wlinux-setup?" 8 45) then
    echo "Starting wlinux-setup."
else
    echo "Exiting wlinux-setup."
    echo "You may run the script again any time by running: $ wlinux-setup"
    exit 0
fi
}

function updateupgrade {
echo "Updating WLinux..."
sudo apt update
sudo apt upgrade -y
sudo apt autoremove -y
}

function createtmp {
    echo "Saving current directory as \$CURDIR"
    CURDIR=$(pwd)
    TMPDIR=$(mktemp -d)
    echo "Going to \$TMPDIR: $TMPDIR"
    cd $TMPDIR
}

function cleantmp {
    echo "Returning to $CURDIR"
    cd $CURDIR
    echo "Cleaning up $TMPDIR"
    sudo rm -r $TMPDIR  # need to add sudo here because git clones leave behind write-protected files
}

function byemessage {
    whiptail --title "Setup is complete." --msgbox "You may run wlinux-setup again any time by typing $ wlinux-setup\n\nYou may open a browser link to get help any time by typing: $ wlinux-help" 8 80
    exit 0
}

# main menu

function installmenu {

CHOICE=$(
whiptail --title "wlinux-setup" --checklist --separate-output "\nHand-curated add-ons [SPACE to select, ENTER to confirm]:" 22 99 15 \
    "LANGUAGE" "Change default language and keyboard setting in WLinux" off \
    "EXPLORER" "Enable right-click on folders in Windows Explorer to open them in WLinux  " off \
    "SHELLS" "Install and configure zsh, csh, and fish" off \
    "EDITORS" "Install text editors neovim, emacs, or Visual Studio Code (requires X)" off \
    "PYTHONPI" "Install Python 3.7 and download and install latest PyPi" off \
    "NODEJS" "Install Node.js and npm" off \
    "GO" "Install the latest Go from Google" off \
    "RUBY" "Install Ruby using rbenv and optionally install Rails" off \
    "RUST" "Install latest version of Rust via rustup installer" off \
    "DOTNET" "Install .NET Core SDK from Microsoft and optionally install NuGet" off \
    "JAVA" "Install the Java OpenJDK and JRE" off \
    "POWERSHELL" "Install PowerShell for Linux and/or Azure CLI tools" off \
    "GUI" "Install the basics needed for most GUI apps and configure GUI options" off \
    "DOCKER" "Install a secure bridge to Docker for Windows" off \
    "CASSANDRA" "Install the NoSQL server Cassandra from Apache" off \
    "NONE" "" on 3>&1 1>&2 2>&3
)

echo "Selected:" $CHOICE

if [[ $CHOICE == *"LANGUAGE"* ]] ; then
  echo "LANGUAGE"
  . /wlinux-setup.d/language
fi

if [[ $CHOICE == *"EXPLORER"* ]] ; then
  echo "EXPLORER"
  . /wlinux-setup.d/explorer
fi

if [[ $CHOICE == *"SHELLS"* ]] ; then
  echo "SHELLS"
  . /wlinux-setup.d/shells
fi

if [[ $CHOICE == *"EDITORS"* ]] ; then
  echo "EDITORS"
  . /wlinux-setup.d/editors
fi 

if [[ $CHOICE == *"PYTHON"* ]] ; then
  echo "PYTHON"
  . /wlinux-setup.d/python
fi

if [[ $CHOICE == *"NODE"* ]] ; then
  echo "NODE"
  . /wlinux-setup.d/nodejs
fi

if [[ $CHOICE == *"GO"* ]] ; then
  echo "GO"
  . /wlinux-setup.d/golang
fi

if [[ $CHOICE == *"RUBY"* ]] ; then
  echo "RUBY"
  . /wlinux-setup.d/ruby
fi

if [[ $CHOICE == *"RUST"* ]] ; then
  echo "RUST"
  . /wlinux-setup.d/rust
fi

if [[ $CHOICE == *"DOTNET"* ]] ; then
  echo "DOTNET"
  . /wlinux-setup.d/dotnet
fi

if [[ $CHOICE == *"JAVA"* ]] ; then
  echo "JAVA"
  . /wlinux-setup.d/java
fi

if [[ $CHOICE == *"POWERSHELL"* ]] ; then
  echo "POWERSHELL"
  . /wlinux-setup.d/powershell
  . /wlinux-setup.d/azurecli
fi

if [[ $CHOICE == *"GUI"* ]] ; then
  echo "GUI"
  . /wlinux-setup.d/gui
fi

if [[ $CHOICE == *"DOCKER"* ]] ; then
  echo "DOCKER"
  . /wlinux-setup.d/docker
fi

if [[ $CHOICE == *"CASSANDRA"* ]] ; then
  echo "CASSANDRA"
  . /wlinux-setup.d/cassandra
fi

if [[ $CHOICE == "NONE" ]] ; then
    echo "NONE"
    whiptail --title "No selection" --msgbox "Please select your desired options using the SPACE bar and then hit ENTER to confirm." 8 80
    installmenu
fi
}

# main

processarguments  "$@"
welcomeprompt
continueprompt
updateupgrade
installmenu
byemessage

exit 0
