#!/bin/sh
# preinst script for wlinux-setup
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#        * <old-preinst> `abort-upgrade' <new-version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    install|upgrade)
    # Check for legacy wlinux-setup and remove if necessary
    if [[ -f "/etc/setup" ]] ; then
        echo "Legacy wlinux-setup script found! Removing"
        rm /etc/setup

        echo "Creating backup of current global profile to profile.old"
        mv /etc/profile /etc/profile.old

        echo "Creating new global profile without legacy wlinux-setup alias"
        grep -v -F "alias wlinux-setup='bash /etc/setup'" /etc/profile.old >> /etc/profile
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
