Document: wlinux-setup
Title: Debian wlinux-setup Manual
Author: <insert document author here>
Abstract: This manual describes what wlinux-setup is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wlinux-setup/wlinux-setup.sgml.gz

Format: postscript
Files: /usr/share/doc/wlinux-setup/wlinux-setup.ps.gz

Format: text
Files: /usr/share/doc/wlinux-setup/wlinux-setup.text.gz

Format: HTML
Index: /usr/share/doc/wlinux-setup/html/index.html
Files: /usr/share/doc/wlinux-setup/html/*.html
