#! /bin/bash

# shellcheck source=./../mocks.sh
source "$(dirname "$0")/../mocks.sh" "$@"

case "${@}" in
  'APPDATA')
    echo 'C:\Users\user\AppData\Roaming'
    ;;
  *)
    echo 'Invalid property'
    ;;
esac
