
name: Spell checking
on:
  push:

jobs:
  build:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
      with:
        # Full git history being used get a proper list of changed files within `spell-checker`
        fetch-depth: 0
    - uses: check-spelling/check-spelling@prerelease
    
