#! /bin/bash

function _pengwin_setup() { #  By convention, the function name
  local cur=${COMP_WORDS[COMP_CWORD]}
  local prev=${COMP_WORDS[COMP_CWORD - 1]}

  case "$prev" in
  EDITORS)
    mapfile -t COMPREPLY < <(compgen -W 'CODE EMACS NEOVIM MSEDIT' -- "${cur}")
    ;;
  GUI)
    mapfile -t COMPREPLY < <(compgen -W 'CONFIGURE DESKTOP NLI GUILIB HIDPI TERMINAL SYNAPTIC WINTHEME WSLG' -- "${cur}")
    ;;
  CONFIGURE)
    mapfile -t COMPREPLY < <(compgen -W 'DISPLAY STARTMENU VCXSRV X410' -- "${cur}")
    ;;
  DESKTOP)
    mapfile -t COMPREPLY < <(compgen -W 'XFCE' -- "${cur}")
    ;;
  TERMINAL)
    mapfile -t COMPREPLY < <(compgen -W 'WINTERM WSLTTY TILIX GTERM XFTERM TERMINATOR KONSO' -- "${cur}")
    ;;
  PROGRAMMING)
    mapfile -t COMPREPLY < <(compgen -W 'C++ DOTNET GO JAVA JETBRAINS JOOMLA LATEX NIM NODEJS PYTHONPI RUBY RUST' -- "${cur}")
    ;;
  NODEJS)
    mapfile -t COMPREPLY < <(compgen -W 'NVERMAN NVM LATEST LTS' -- "${cur}")
    ;;
  PYTHONPI)
    mapfile -t COMPREPLY < <(compgen -W 'PYENV PYTHONPIP POETRY' -- "${cur}")
    ;;
  SERVICES)
    mapfile -t COMPREPLY < <(compgen -W 'LAMP RCLOCAL SSH SYSTEMD' -- "${cur}")
    ;;
  LAMP)
    mapfile -t COMPREPLY < <(compgen -W 'BUILTIN 10.6 10.7 10.8 10.9' -- "${cur}")
    ;;
  SETTINGS)
    mapfile -t COMPREPLY < <(compgen -W 'EXPLORER COLORTOOL LANGUAGE SHELLS' -- "${cur}")
    ;;
  SHELLS)
    mapfile -t COMPREPLY < <(compgen -W 'BASH-RL CSH FISH ZSH' -- "${cur}")
    ;;
  TOOLS)
    mapfile -t COMPREPLY < <(compgen -W 'ANSIBLE CLOUDCLI DOCKER HOMEBREW POWERSHELL' -- "${cur}")
    ;;
  CLOUDCLI)
    mapfile -t COMPREPLY < <(compgen -W 'TERRAFORM' 'KUBERNETES' -- "${cur}")
    ;;
  *)
    mapfile -t COMPREPLY < <(compgen -W "--debug -d --verbose -v -y --yes --assume-yes --noupdate --norebuildicons -q \
    --quiet --noninteractive -w --whiptail -n --ncurses --dialog --alt --multiple --help \
    upgrade autoinstall install uninstall remove startmenu \
    EDITORS GUI MAINTENANCE PROGRAMMING SERVICES SETTINGS TOOLS UNINSTALL" -- "${cur}")
    ;;
  esac

  return 0
}

complete -F _pengwin_setup pengwin-setup
complete -F _pengwin_setup ./pengwin-setup
